server:
  port: 8020
zuul:
  ignoredServices: '*'
  routes:
    slerp-io: /slerp-io/**
    slerp-oauth: /slerp-oauth/**
security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:8019/oauth/token
      userAuthorizationUri: http://localhost:8019/oauth/authorize
      clientId: 26fb9f8d36b892e043f4a8b107809ac2960e73e0
      clientSecret: f3b501072306261738deef3f7d1e8df668be32be
    resource:
      jwt:
        keyUri: http://localhost:8019/oauth/token_key
