server:
    port: 10000
zuul:
    ignoredServices: '*'
    routes:
        slerp-io: /slerp-io/**

security:
    user:
        password: none
    oauth2:
        client:
            accessTokenUri: http://localhost:8019/oauth/token
            userAuthorizationUri: http://localhost:8019/oauth/authorize
            clientId: 26fb9f8d36b892e043f4a8b107809ac2960e73e0
            clientSecret: 123456
        resource:
            jwt:
                keyUri: http://localhost:8019/oauth/token_key

---
spring:
    profiles: heroku
server:
    port: ${PORT:0}



security:
    oauth2:
        client:
            accessTokenUri: https://belajar-springcloud-auth.herokuapp.com/user/oauth/token
            userAuthorizationUri: https://belajar-springcloud-auth.herokuapp.com/user/oauth/authorize
            clientId: onlinestore
            clientSecret: 123456
        resource:
            jwt:
                keyUri: https://belajar-springcloud-auth.herokuapp.com/user/oauth/token_key
