name: Slerp Product Service Testing

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/product-service
    username: postgres
    password: rioters7
    driverClassName: org.postgresql.Driver
