version: '2.1'
services:  
  config-server: 
    build: config-server
    ports:
      - 8888:8888

  discovery-service:
    build: discovery-service
    ports:
      - 8761:8761
  api-gateway:
    build: api-gateway

  slerp-io-api:
    build: slerp-io-api
    ports:
      - 8019:8019
