version: '3'
services:
  slerp-io-oauth-api:
    environment:
      CONSUL_SERVER: http://172.17.0.1
      SPRING_PROFILES_ACTIVE: docker
    ports:      
      - "8019:8019"
    build: slerp-io-oauth-api
    image: localhost:5000/slerp/slerpio-oauth-api
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: '10'
 
