---
flyway:
  enabled: true
  locations: classpath:migration
spring:
  profiles: docker
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://pg_test:5432/slerp
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: kiditzbastara@gmail.com
    password: NullPointerException
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  activemq:
    user: admin
    password: admin
    broker-url: tcp://activemq:61616
slerp:
  oauth:
    url: http://slerp-oauth-api:8019/
---    
flyway:
  enabled: true
  locations: classpath:migration  
spring:
  profiles: dev
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/slerp
    username: postgres
    password: rioters7 
    driverClassName: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: kiditzbastara@gmail.com
    password: NullPointerException
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
slerp:
  oauth:
    url: http://localhost:8019/