name: Slerp Product Service Testing

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/slerp-io
    username: postgres
    password: rioters7
    driverClassName: org.postgresql.Driver
