---
kafka: 
  address: 172.17.0.1:9092
  groupId: slerp
  messages: 
    register: slerp_register
flyway:
    enabled: false
spring: 
  profiles: docker
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.postgresql.Driver
    username: kiditz
    password: rioters7
    url: jdbc:postgresql://172.17.0.1:2070/slerpio  
  mail:
    host: smtp.gmail.com
    port: 587
    username: kiditzbastara@gmail.com
    password: NullPointerException
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
server:
  port: 8020

redis: 
  hostname: localhost
