server:
    port: ${PORT:0}

spring:
    jackson:
        serialization:
            indent_output: true

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8017/eureka/,http://localhost:8016/eureka/
    instance:
        instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}
