kafka: 
  address: 172.17.0.1:9092
  groupId: slerp
  messages: 
    register: register
    rm_user_principal: remove_user_principal
    mail_regiter: mail_register
    edit_user : edit_user_principal
flyway:
    enabled: false
