---
spring: 
  profiles: docker
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
    username: kiditz
    password: rioters7
    url: jdbc:postgresql://192.168.43.42:2070/oauth

  mail:
    host: smtp.gmail.com
    port: 587
    username: kiditzbastara@gmail.com
    password: NullPointerException
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
server:
  port: 8019
  session:
    cookie:
      name: AUTHSERVER